name: github_search
description: My Flutter exercise project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6

  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  device_preview_screenshot: ^1.0.0
  device_preview: ^1.1.0
  dio: ^4.0.6
  equatable: ^2.0.5
  infinite_scroll_pagination: ^3.2.0
  json_annotation: ^4.7.0
  liquid_pull_to_refresh: ^3.0.1
  pager: ^0.0.5
  shared_preferences: ^2.0.15
  stream_transform: ^2.1.0
  swipeable_page_route: ^0.2.6
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
